Squashed commit of the following:
commit 01d7f78ed2d1c706c6928e12db7d27f795fc6062
Author: Fuad2Dev <94391454+Fuad2Dev@users.noreply.github.com>
Date:   Fri Oct 14 16:30:31 2022 +0000

    #93 survey control buttons

commit 6a75b14379f69b3fdb25a49348fd9f7989390018
Author: Fuad2Dev <94391454+Fuad2Dev@users.noreply.github.com>
Date:   Fri Oct 14 15:02:01 2022 +0000

    #94 dynamic survey expiration date

commit 54a4132e0e3119580849d3e5c6fa91f9cce9e58d
Merge: b9dcc7f 530e0ac
Author: Fuad2Dev <94391454+Fuad2Dev@users.noreply.github.com>
Date:   Fri Oct 14 14:07:56 2022 +0000

    Merge branch 'ui-tests' into dev

commit 530e0ac8c7e041556b56cc710be42c25139eccc0
Author: Fuad2Dev <94391454+Fuad2Dev@users.noreply.github.com>
Date:   Fri Oct 14 14:07:31 2022 +0000

    expiration-date show UI update

commit 44863f913b7b805972da069faeaa2616ccbd46ce
Author: josh-boat365 <nyarko.boateng20@outlook.com>
Date:   Thu Oct 13 23:34:14 2022 +0000

    UI update: #90 feature-> editable expiration date

commit 1cdc5d001490ca1943e8a19cd8984d21c650dd61
Author: josh-boat365 <nyarko.boateng20@outlook.com>
Date:   Thu Oct 13 23:11:32 2022 +0000

    UI update: #90 feature-> editable expiration date

commit 44ccd6d3fd3dd79d8081c0f2df0cf8c27bcdb21f
Author: josh-boat365 <nyarko.boateng20@outlook.com>
Date:   Thu Oct 13 22:15:19 2022 +0000

    UI update: #94 enhancement->show expiration date on survey dev page

commit 15f7e370dcc1466d2100cec0425d9d08c95fc347
Author: josh-boat365 <nyarko.boateng20@outlook.com>
Date:   Thu Oct 13 18:45:47 2022 +0000

    UI update :+1:  made question cards responsive

    Made grid question type responsive on alumnus.
    Made question cards responsive.

commit b9dcc7f0d67876fe422a160d613d7d6a33bfce50
Author: Fuad2Dev <94391454+Fuad2Dev@users.noreply.github.com>
Date:   Thu Oct 13 17:47:03 2022 +0000

    Update AppServiceProvider.php

    reason: adjusting to mixed content on secure connections
    error: assets are served on a less secure protocol
    fix: force all transfer protocols to serve securely on particular environments